topic_name:
  vehicle_state: /app/loc/novatel_geo
  
# Common variables
common_variable:
  dataset: kitti # novatel kitti 
  lidar_topic_name: /velodyne_points # /ouster/points /velodyne_points /scala_gen2_points /moe_points
  lidar_type: kitti # ouster vlp32 kitti scala moe
  projection_mode: Cartesian
  use_init_lat_lon: true # if true, do not need ref below
  ref_latitude: 37.589 # howon 37.589 # pangyo 37.399
  ref_longitude: 127.157 # howon 127.157 # pangyo  127.109
  novatel_heading_bias_deg: 0.0 # pangyo -0.5

range_pmc:
  deskewing: true

  # Range comparison
  vertical_neighbor_pixel: 2
  horizontal_neighbor_pixel: 2

  # Range image config
  range_threshold: 0.3
  max_range_image_num: 10
  height_filter: false

  min_key_frame_time: 0.18
  min_key_frame_rot: 3.0

  ground_angle: 10 # deg 17.4%

  # Clustering
  dist_threshold_m: 0.5
  segment_min_point_num: 30
  segment_valid_point_num: 5
  segment_valid_line_num: 3

  moving_confidence: 0.3 # 0.3
  static_confidence: 0.15 # 0.15
  gaussian_sigma: 1.0 # 0.4 쎄게, 0.8 약하게
  static_gaussian_sigma: 1.5 # deprecated
  dynamic_gaussian_sigma: 2 # 클수록 넓게 전파 1 -> 2.1m  4 -> 8.7m 8 -> 17m
  sigma_epsilon: 0.05 # 최소 sigma 값.

  ground_filtering: true # ground filtering을 true로 해야 cluster level filtering 가능 
  cluster_level_filtering: true # deprecated
  
  run_case_2: true
  run_small_dynamic_filtering: true
  min_voxel_cluster_num: 20 # 복셀 클러스터의 최소 복셀 개수
  
  run_region_growing: true

  output_static_point: false
  output_discrete_label: true
  output_min_range: false
  debug_image: true

  run_evaluation: true
  evaluation_dataset: kitti # kitti moe
  
moe_evaluation:
  pcd_folder_path: /mnt/c/Users/Alien02/Documents/rosbag/moe/04/pcd/
  label_folder_path: /mnt/c/Users/Alien02/Documents/rosbag/moe/04/label/
  pose_file_path: /mnt/c/Users/Alien02/Documents/rosbag/moe/04/gt_poses.txt

  result_bag_path: /mnt/c/Users/Alien02/Documents/rosbag/moe/04/result.bag

# Task ID
task_id:
  ## RTE
  id_tf_frame: 10

# Task period [s]
task_period:
  ## RTE
  period_tf_frame: 0.005
  period_tf_static_frame: 1
