topic_name:
  vehicle_state: /app/loc/novatel_geo
  
# Common variables
common_variable:
  dataset: kitti # novatel kitti
  lidar_topic_name: /velodyne_points # /ouster/points /velodyne_points
  lidar_type: kitti # ouster velodyne kitti
  projection_mode: Cartesian
  use_init_lat_lon: true # if true, do not need ref below
  ref_latitude: 37.589 # howon 37.589 # pangyo 37.399
  ref_longitude: 127.157 # howon 127.157 # pangyo  127.109
  novatel_heading_bias_deg: -0.5 # howon 0.6 # pangyo -1.0

  ego_to_lidar_transform:
    x: 1.2
    y: 0.0
    z: 1.6
  ego_to_lidar_rotation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

range_pmc:
  deskewing: true
  # horizontal_resolution: 0.703125   # deg OS1-512
  # vertical_resolution: 0.354330     # deg OS1-512
  # horizontal_resolution: 0.4        # deg VLP32
  # vertical_resolution: 0.5          # deg VLP32
  horizontal_resolution: 0.1728     # deg KITTI
  vertical_resolution: 0.4          # deg KITTI

  min_range: 0.5
  max_range: 50
  range_threshold: 0.5
  max_range_image_num: 10
  min_occluded_num: 7
  neighbor_pixel_max: 4

  min_key_frame_time: 0.0
  min_key_frame_rot: 3.0
  
  # fov_up: 22.5      # OS-1 512
  # fov_down: -22.5   # OS-1 512
  # fov_up: 15        # VLP32
  # fov_down: -25     # VLP32
  fov_up: 2.0       # KITTI
  fov_down: -24.9   # KITTI

  fov_left: 180.0
  fov_right: -180.0
  height_filter: false

  ground_angle: 5 # deg

  dist_threshold_m: 1.0
  segment_min_point_num: 50
  segment_valid_point_num: 8
  segment_valid_line_num: 3

  moving_confidence: 0.5
  static_confidence: 0.3
  gaussian_sigma: 12

  cluster_level_filtering: true

  output_static_point: false
  output_min_range: true
  debug_image: true
  

# Task ID
task_id:
  ## RTE
  id_tf_frame: 10

# Task period [s]
task_period:
  ## RTE
  period_tf_frame: 0.005
  period_tf_static_frame: 1
