moe:
  horizontal_resolution: 0.1   
  vertical_resolution: 1.05 # seq 00 64ch
  # vertical_resolution: 1.4 # seq 02 32ch

  min_range: 0.2
  max_range: 100
  max_points_in_pixel: 3
  
  # seq 00
  fov_up: 22.5    
  fov_down: -45.0

  # seq 01
  # fov_up: 12  
  # fov_down: -45.0

  # seq 02
  # fov_up: 22.5    
  # fov_down: -22.5

  
  fov_left: 180.0 
  fov_right: -180.0 

  ego_to_lidar_transform:
    x: 0.0 
    y: 0.0 
    z: 0.0 
  ego_to_lidar_rotation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0 
