ouster:
  horizontal_resolution: 0.35156 # 0.703125   
  vertical_resolution: 0.3307   

  min_range: 0.7
  max_range: 100
  max_points_in_pixel: 3
  
  fov_up: 20.96    
  fov_down: -21.05  

  fov_left: 180.0 
  fov_right: -180.0 

  ego_to_lidar_transform:
    x: 1.2 
    y: 0.0 
    z: 1.7 
  ego_to_lidar_rotation:
    roll: 0.0
    pitch: -1.0
    yaw: -2.0 
